when:
  - event:
    - push

steps:
  - name: backend-test
    image: golang:1.25
    commands:
      - go install golang.org/x/tools/gopls@latest
      - make backend-lint
      - make backend-test COVERAGE=1

  - name: frontend-test
    image: node:24
    commands:
      - mkdir -p build
      - cd frontend
      - npm install
      - npm run lint
      - npm run test:coverage
      - npm run benchmark
      - cp -ar coverage ../build/coverage

  - name: build-frontend
    image: node:24
    depends_on:
      - frontend-test
    commands:
      - make frontend-prod

  - name: build-backend
    image: golang:1.25
    depends_on:
      - backend-test
      - build-frontend
    commands:
      - make prod-all
      - gzip build/wesplot-* # https://codeberg.org/woodpecker-plugins/plugin-s3/issues/328

  - name: upload
    image: woodpeckerci/plugin-s3
    depends_on:
      - build-backend
    when:
      - event: push
        branch: main
    settings:
      endpoint:
        from_secret: s3_endpoint
      bucket:
        from_secret: s3_bucket
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      source: build/**/*
      target: /wesplot/releases/${CI_PIPELINE_NUMBER}
      strip_prefix: build/
