on:
  push:
    branches:
      - main
      - "releases/**"

name: wesplot-release

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - run: .github/build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: wesplot-binaries
          path: build/
          if-no-files-found: error
